# Config exemple

# path to server files
path = "./server/"

# global servers config
[servers]
index = "index.html" # define the index (entry point) file default index.html
not_found = "404.html" # define the 404 file not found file
aliases = {"hello.html" = "/world"} # create aliases (file : path) if empty will use the file name for path (hello.html = hello)

# Creating an instance
[[servers.instance]]
address = "127.0.0.1" # define the instance ip address
ports = [8080,8081,8082] # define the instance listening port

[[servers.instance]]
address = "127.0.0.2"
ports = [8082,8083]